### ISSUE TITLE
Define Collections as a set a projects

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#519]
A Collection is a set of projects with minimum consistent settings/data, and some specific data.

## Data:
The following fields are needed at Collection level as they will be used as data sources for EMODnet exports.
* Title (of type text) -> mapped to Dataset title, defaults to nothing, help text to get from EMODnet guidelines.
* Contact (of type User) -> mapped to Contact person, defaults to a common Manager for all projects, None if no such user.
* Creators (of type 'list of User') -> mapped to Data creator, defaults to all annotators, including historical ones, for all included projects. 
* Associates (of type 'list of User') -> mapped to Associated persons, defaults to empty.
* Citation (of type text) -> mapped to Dataset Citation, help text to get from EMODnet guidelines.
* License (of type 'License') -> mapped to Licence, computed as the most restrictive of all licenses of included projects. 
* Abstract (of type text) -> mapped to Abstract, help text to get from EMODnet guidelines. Max 1000 chars.
* Description (of type text) -> mapped to Description, help text to get from EMODnet guidelines.

## Functions:
Creators list can be amended, i.e. a person can be added or removed.
Associates list can be amended as well. A User should not be in both Creators and Associates lists.
License cannot be edited, but should be visually signaled when it prevents export.

**Comment by rkiko** [comment]
Collection definition: "view-only" and "sorting-enabled"

(((this is a summary of a communication on click-up, due to issues with sorting for Thelma's and Laetitia's thesis, I asked collection development to be enhanced)))

JO: Regarding collections, they will have to be only a thin aggregation layer on top of projects (because of all the machinery already in place at project level that we cannot just delete/change); their sole goals are (1) allow browsing/visual comparison of sorting across projects, (2) export of several projects as a single dataset. Most settings, permissions etc. will stay at project level. Also, projects could belong to several collections. So there is unfortunately no easy way of enforcing what you're thinking about. I guess we'll never replace good old coordination between actual people 😉


I think that apart from this "view-only" collection type, we should also think about a "sorting-enabled" collection type. This will be more complicated, but should enable cross-project sorting, without the problems we ran into with the subsets...

important features:
 "view-only": 
1) no-sorting allowed!!!
2) check for temporary classes, they should not exist in original projects or should not be merged

 "sorting-enabled": 
1) sorting to be blocked in original projects (((requires a field in original projects that indicates in which collection an image is used. If the field is filled, sorting needs to be blocked in the original project)))
2) once sorting of a collection is finished (e.g. for publication), it needs to be archived, only then sorting in individual projects should be allowed again. 
3) images that are part of an archived collection should also be marked as such, to make people think twice before they resort.
4) importantly, images should not be duplicated!!!
5) temporary classes should not be merged
