### ISSUE TITLE
Subset (and probably other actions) fail with very long URLs

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#842]
On project https://ecotaxa.obs-vlfr.fr/prj/6433 which has many samples, once a selection of ~half of them is made, using Filtered > Subset results in an error 414 - Request URI Too Large (displayed by Nginx). I am not sure if this is a limitation of the config of nginx or something unsolvable because URIs have a hardcoded maximum length.

Here is the URL giving rise to the error
[ectaxa_url.txt](https://github.com/ecotaxa/ecotaxa_front/files/10345050/ectaxa_url.txt)

**Comment by grololo06** [comment]
#716 fix was apparently not enough

**Comment by grololo06** [comment]
#656 was similar but before the move to docker infrastructure

**Comment by grololo06** [comment]
Added into nginx config:
```
# vi /etc/nginx/sites-available/ecotaxa

server {
        listen 443 default_server;

.
.
.
        large_client_header_buffers 4 16k;

```

**Comment by grololo06** [comment]
Need also to adjust the max size (32K needed) in the front docker, @see: https://github.com/ecotaxa/ecotaxa_front/blob/a8f6e22bcfc0f422194876e614f549f4e3a28cff/docker/prod_image/uwsgi.ini#L10

Until image rebuild, a temp solution is to adjust it inside the running image, e.g.:
```
# docker exec -it ecotaxafront /bin/bashroot@7e75997c39fb:/app# vi uwsgi.ini
... adjust param
root@7e75997c39fb:/app# kill -SIGHUP 1
... restarts uwsgi
```

**Comment by grololo06** [comment]
Root cause:  while the [plain origin page with filters](https://ecotaxa.obs-vlfr.fr/prj/6433?samples=410059,410247,410910,412391,409811,410103,411199,412233,410065,410482,411053,413851,412335,409693,410082,411043,414000,412389,409713,410109,411183,413828,412236,409523,410168,411033,413897,412303,409682,410146,411189,413993,410066,410218,411242,413792,409965,410452,413752,409739,410472,413987,409660,410124,413841,409550,410093,413826,409938,410265,413996,409674,410389,414017,409645,410445,413906,409538,410286,414003,409654,410362,413628,410021,410354,413900,410052,410143,413708,409879,410495,413754,409782,410409,413714,409816,410112,413695,409896,410367,413700,409706,410324,413613,409997,410274,409636,410294,409807,410436,413789,409584,410385,413769,409679,413800,409981,413664,409689,410234,413588,409536,410393,413784,409738,410341,413581,409705,410180,413612,409565,410360,413687,409894,410117,413638,409742,410233,413756,409937,410205,413639,409826,410165,409958,410275,409691,410448,409873,410214,409728,410338,409864,410419,409556,410456,409723,410125,409701,410353,409951,410300,409528,410232,409787,410319,409702,410322,409762,410259,409588,410305,409944,410311,409530,410235,409617,410075,409687,410317,410527,409885,410355,410653,410004,410160,410642,409690,410412,410648,409759,410295,410552,409957,410212,410702,409635,410417,410551,409970,410416,410811,409743,410078,410535,409844,410368,410739,409800,410292,410786,409786,410442,410877,409673,410636,411880,409628,410545,411724,409867,410618,411900,409751,410614,411859,410849,411870,410729,412033,410731,411895,410867,411802,410848,411898,410873,411768,410761,411808,410771,411886,410529,411844,410833,411824,410769,411779,410865,411829,410604,411796,410758,411860,410774,411849,410754,411887,410756,411792,410840,411738,410746,412021,410725,411845,410747,411835,410645,411788,410520,411842,410714,411939,410718,411833,410809,411851,410844,411708,410864,411754,410800,411814,410783,411855,410770,412022,410817,412043,410726,412045,410733,411746,410723,411783,410711,411727,410549,411731,410590,411946,410602,411852,410730,411733,410869,413921,411807,410762,413982,411745,410831,411817,410652,411729,410640,413801,411778,410721,413818,411777,410634,413984,411826,410609,413762,411983,410695,413902,411806,410847,413884,411736,410794,411226,414007,411972,410690,410983,413899,411856,410851,411149,413892,411769,410825,411126,414012,411707,410612,411135,413724,411858,410797,411014,413642,411872,410534,411235,413880,411790,410577,411171,413650,411827,410872,411026,413986,411883,410866,411151,414004,411945,410734,411003,414018,411812,410753,411157,414002,411913,410661,411004,413688,411748,410728,410982,413933,411926,410827,410912,413994,411894,410839,411210,413920,411974,410727,410974,414020,411924,410838,411138,413981,411735,410820,411167,414009,411752,410858,411002,413989,411865,410706,411124,413930,411787,410624,411180,413938,411813,410715,411230,413952,411868,410860,411132,413916,411890,410743,411079,413775,411879,410870,411108,413696,411819,410555,413998,411999,410688,413959,411718,410608,411046,413722,411798,410856,411154,413748,412025,410855,413863,411742,410607,413786,411958,409851,410749,411203,412046,409961,410843,411117,412053,409900,410821,411233,413651,411877,409539,410542,411094,413807,411720,409865,410732,410920,413950,411997,410024,410868,411219,413857,411702,410039,410635,411078,413773,411766,410035,410677,411177,413875,411948,409969,410874,410899,413849,411954,409605,410853,410961,413896,411839,409560,410693,411102,413862,411973,409952,410819,411238,413812,411902,409813,410565,411145,413889,411749,409852,410750,411027,413781,412013,409683,410641,410962,413911,411990,410023,410556,410928,413686,412000,409770,410879,411147,413983,411904,409875,410751,411176,413829,411947,409572,410735,411214,413629,411901,409611,410523,410882,413876,411785,409726,410669,411076,413771,412001,409524,410808,411128,413946,411967,409711,411237,413852,410011,411041,413758,410036,411058,413977,409893,411201,414014,409664,414015,409974,413840,409916,410917,413901,409863,410990,413601,410049,411249,413868,409579,411246,413839,409860,411192,413718,409752,411097,413604,409855,411084,413782,409621,411090,413755,409537,410903,413882,409696,411134,413825,409808,411255,414016,409655,411005,413630,409806,411059,413619,409714,411248,413951,409859,410890,413753,409595,410944,413772,409837,410329,411105,413736,409559,410498,410919,413734,409920,410361,411212,413690,409727,410461,411113,413774,409831,410443,411093,413595,409817,410475,411072,413699,409533,410080,411160,413719,410010,410170,411037,413672,409890,410331,411064,409620,410441,411127,410030,410468,411211,413620,409849,410145,411152,413663,409542,410481,410906,413676,409571,410105,410930,413691,409722,410307,411074,413647,409818,410127,411111,413770,409986,410397,411164,413610,409665,410211,411186,413744,409950,410186,411057,413616,409757,410383,410918,413733,409892,410334,411007,413634,409557,410183,411139,413732,409606,410390,411217,413794,409634,410181,411165,413730,409943,410462,411173,413793,410009,410464,410881,413715,409659,410306,411185,413644,409886,410325,411101,413787,409989,411073,410043,411209,410069,410288,411196,413602,409734,410438,410959,413709,409745,410079,410897,413591,409929,410399,411104,413617,409878,410074,411031,413670,409769,410110,411006,413768,409532,410237,413592,409650,410194,413625,409592,410478,413646,409653,410299,413627,410062,410198,413692,409872,410426,413654,409866,410185,413683,409763,410191,413689,410038,410137,413658,409915,410098,413728,410022,410187,413685,409631,410291,413607,409832,410084,413596,410014,410077,413586,409908,410072,413716,409707,410254,413614,409966,410440,413783,409522,410167,413717,409703,410095,413608,409630,410246,413599,409840,410333,413633,409599,410406,413662,409764,410192,413623,409668,410388,413656,409876,410155,413713,409910,410428,413587,409686,410159,409567,410437,409880,410377,409675,410139,409661,410208,409602,410310,409940,410447,410042,410087,409917,410444,409923,410142,409750,410177,409692,410379,409854,410158,409975,410206,409758,410327,409566,410190,409527,410169,409718,410264,409626,410454,409983,410157,409553,410094,409964,410439,409574,410108,409870,410332,409610,410316,409822,410277,409797,410176,409935,410404,409956,410477,409615,410342,409933,410195,409960,410369,410045,410394,409911,410321,409709,410256,409781,410153,409843,410386,409563,410297,409778,410219,409947,410431,409589,410123,409871,410506,409902,410140,409982,410315,409820,409925,409593,410067,409573,409576,409941,410057,410048,409810,410007,410050,409819,409978,410041,410019,409568,409973,409904,410063,410028,409715,409629,410015,409962,409977,409967,409773,409677,410055,409671,409963,409638,409861,409699,409594,409891,409992,409603,409869,409823,409649,409792,409784,409928,409888,410003,409622,409756,409838,409767,409591,409724,410006,409972,409887,409897,409881,409669,409953,409558,409531,409729,409858,409545,409848,409971,409949,409765,409776,410301,410128,410266,410225,410282,410138,410433,410215,410216,410302,410278,410303,410357,410236,410262,410318,410320,410115,410088,411222,410415,410989,410336,411170,410163,410965,410076,411035,410392,410975,410414,410857,411096,410285,410709,411159,410484,410557,411254,411975,410427,410790,411187,411772,410425,410804,411018,411987,410283,410807,410889,412058,410491,410611,410987,412007,410132,410766,410947,412031,410469,410796,411179,412017,410258,410713,411060,411810,410471,410850,411109,412038,410381,410775,411133,411892,410178,410785,410911,411893,410096,410793,410993,412051,410363,410789,411229,413865,412047,410156,410806,411205,413847,412040,410458,410787,411065,413864,411985,410424,410716,411070,413866,412034,410510,410628,411168,413740,411941,410104,410564,411251,413991,412044,409862,410691,411223,413934,409780,410859,411155,413967,409993,410515,410878,411130,413879,411951,409570,410513,410562,411245,413971,411960,409868,410509,410659,411227,413923,412016,409924,410502,410680,411129,413795,411923,409903,410499,410781,411118,413815,411882,412139,409945,410488,410675,410960,413895,411838,412204,409877,410501,410528,411086,414011,412005,412325,409979,410263,410763,411071,413697,412030,412283,409694,410490,410798,411194,413917,411721,412221,409907,410161,410643,411218,413856,411982,412353,409959,410339,410586,411022,413909,411909,412292,409842,410384,410764,411012,413640,411821,412455,409824,410152,410722,411156,413968,411840,412298,409642,410330,410621,411228,413838,411740,412362,409968,410430,410685,411040,413988,411953,412153,409976,410489,410537,410896,414010,411794,412446,410008,410134,410582,411019,413745,411908,412137,409789,410497,410684,411131,413860,411850,412152,409548,410466,410826,410991,413980,411995,412164,410000,410500,410592,411082,413802,411780,412426,409931,410101,410876,411061,413905,411744,412314,410064,410154,410593,411204,413956,411912,412207,409914,410352,410854,410988,413837,411929,412413,409805,410435,410696,411000,413887,411809,412174,409652,410196,410788,410929,413798,412018,412442,409777,410463,410835,411243,413893,412032,412351,409815,410842,411008,413694,411940,412415,409794,410815,410979,413721,411854,412440,409586,410514,410698,410937,413942,411942,412347,409697,410511,410777,411195,413960,411725,412334,409740,410343,410824,411088,413878,411922,412418,410001,410224,410836,411083,413973,411782,412208,409999,410372,410588,411024,413873,411981,412382,409845,410460,410740,410943,413926,411978,412317,410068,410304,410813,411184,413643,411823,412380,409926,410473,410861,410908,413597,411726,412376,410051,410250,410829,411100,413949,411804,412228,409801,410253,410863,411054,413767,411805,412104,410027,410136,410671,411021,413657,412256,410053,410492,410875,411208,413936,412361,409814,410474,410862,411182,413827,411815,412281,409569,410193,410561,411144,413990,411915,412116,409578,410459,410801,411010,413636,411756,412185,410061,410496,410845,410892,414005,411791,412074,409828,410171,410757,411038,413932,411715,410037,410070,410518,410966,413957,411703,410029,410358,410830,411142,413995,412110,410056,410401,410818,411066,413624,412177,409554,410323,410615,411050,413796,411732,412169,409874,410485,410852,411080,413872,411771,412257,409798,410396,410846,411099,413861,411996,412167,409919,410255,410657,410923,413615,411739,412338,409841,410422,410736,411009,413853,411816,412423,409985,410244,410776,410981,413678,411800,412160,409922,410476,411169,413867,411871,412124,409998,410276,411023,413965,411774,412200,409856,410410,411085,414019,411919,412145,409670,410217,411115,413777,411980,412456,409909,410375,410968,413751,411991,412061,409732,410370,411234,413955,411910,412201,410058,410241,411045,413785,411891,412270,409623,410081,411042,413830,411956,412154,410016,410148,411216,413749,411965,412296,410044,410287,410909,413850,411857,412087,409994,410347,411206,413843,411968,412076,409850,410309,411174,413747,411776,412432,409901,410213,410951,413908,411979,412252,410060,410413,411161,413979,411723,412333,409857,410411,410885,413820,411966,412066,409783,410071,411121,413945,411918,412143,409906,410314,413928,412039,412439,410018,410508,413589,411889,412412,409790,410238,411178,413674,411952,412218,409802,410326,411055,413844,412042,412274,409625,410380,410978,413831,411797,412269,409990,410337,411077,413842,412002,412133,409681,410222,411153,413710,412383,409827,410378,411191,413915,412355,409746,410172,410901,413898,412305,409772,410268,411232,413869,412132,409748,410243,411095,413824,412223,409590,410207,411016,413701,412285&taxochild=N) send "only" a 12K URL, choosing to Subset composes a request where sample names are in a list: 410059,410247,410910.. which URL Encoded gives: 410059%2C410247%2C410910 -> 2 more chars per sample ID -> more than 16K in total with the rest of HTTP request e.g. auth cookies. 
There is probably no real need for this URLEncode

**Comment by bea777515** [comment]
a solution will really be needed with collections  (more samples )
